"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";
import Context from "@/context/AuthContext";
import { QueryClientProvider, QueryClient } from "react-query";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const queryClient = new QueryClient();

  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.css"
          integrity="sha512-tx5+1LWHez1QiaXlAyDwzdBTfDjX07GMapQoFTS74wkcPMsI3So0KYmFe6EHZjI8+eSG0ljBlAQc3PQ5BTaZtQ=="
        />
      </head>
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <Context>
            <Layout>{children}</Layout>
          </Context>
        </QueryClientProvider>
      </body>
    </html>
  );
}
